### ISSUE TITLE
Homepage content disappears when switching to another tab

### ISSUE THREAD

**Issue by Nomnomburger** [elapse-vrc/elapse-app#31]
When setting the `afterCurrentDate` flag to `false` on the homepage, entering the team number works as expected, and past events show up. But, **when switching to another tab and back, the content will disappear.** After editing the team number and saving will bring up the result. 

This bug is probably cause by the screen not reading the intialText once you go in, and can probably be fixed by adding that to the `initState()`. Or, possibly it can be fixed with the method used in `matches.dart`, whatever that method is.

This will be fixed in alpha v0.0.4

**Comment by a-fyn** [comment]
Yeah, I think I just need to add it to the `initState()`.

**Comment by Nomnomburger** [comment]
yea i tried that, but i dont really know why it doesnt work lol. Maybe you can point me in the right direction? :)

**Comment by a-fyn** [comment]
Can you tell me exactly what you tried?

**Comment by Nomnomburger** [comment]
I made a function that reads the sharedprefs team value, and put the function in initState

**Comment by a-fyn** [comment]
Can you commit the code?

**Comment by Nomnomburger** [comment]
there is no code for it, deleted it lol

**Comment by Nomnomburger** [comment]
@a-fyn did we fix this yesterday lol

sorry i have terrible memory

**Comment by a-fyn** [comment]
yes
